### ISSUE TITLE
inline seems to remove whitespace

### ISSUE THREAD

**Issue by jeapostrophe** [wilbowma/scribble-minted#2]
I am using the inline version and `@mintinline["javascript"]{const A = B;}` is rendered as `constA=B;` with no spaces. The HTML is

```
<code class="highlight-inline"><span class="kr">const</span> <span class="nx">LHS</span> <span class="o">=</span> <span class="nx">RHS</span><span class="p">;</span></code>
```

I get the behavior I want when I remove `display: inline-table`

**Comment by wilbowma** [comment]
What browser are you using? I can't reproduce, but I had another report of a similar issue that seemed browser dependent.

**Comment by wilbowma** [comment]
Maybe addressed by 23cfd9d8be60925d56407686b6bc5f5bf18a7eef

**Comment by wilbowma** [comment]
Tested in Chromium and Firefox, seems to work.

**Comment by wilbowma** [comment]
Also seems to work on iOS safari. Closing.
