### ISSUE TITLE
pygment style to mimic scribble colors

### ISSUE THREAD

**Issue by jeapostrophe** [wilbowma/scribble-minted#3]
I'd like to have a style that matches the rest of Scribble's color scheme for code. I found an example --- https://github.com/shkumagai/pygments-style-solarized/blob/develop/pygments_style_solarized/light.py --- and it looks like you need to match 80 colors. This seems really painful but doable. I hope someone that's not me will do it :)

**Comment by jeapostrophe** [comment]
We made something like this --- https://github.com/reach-sh/reach-lang/blob/master/docs-src/minted.css

**Comment by wilbowma** [comment]
I've improved the style support, and added this style 3ac57944a358cedb02a30f3c24adca8322082dcb

It now supports the ability to add custom styles, although I've not exposed the interface nor documented it so...

**Comment by jeapostrophe** [comment]
Cool thanks!
